// js/market-report.js

let _mrReportId  = null;   // SharePoint item ID when editing a saved report
let _mrRoleId    = null;   // Selected role ID (string)
let _mrProjectId = null;   // Selected project ID (string)
let _mrTam       = null;   // TAM value (number)
let _mrTitle     = "";     // Report title
let _mrObs       = "";     // Observations HTML from rich text editor
let _mrData      = null;   // Cached { activity, role, rejections }

// Library state (N-245)
let _mrLibraryCache  = [];  // all saved reports, from the last load — unscoped,
                             // every user with module access sees every report
let _mrLibraryFilter = '';  // '' = all clients
let _mrTpMap         = {};  // CreatedByEmail (lower-case) -> display name
let _mrProjectMap    = {};  // projectId (string) -> CustomerName, for banding
let _mrRoleProjectMap = {}; // roleId (string) -> projectId (string)

async function renderMarketReport() {
  const main = document.getElementById("main-content");
  const user = getCurrentUser();
  _mrData = null;

  const roles  = await getScopedRolesVisibleTo(user.email, _mrResolvedRole);
  const saved  = await getMarketReports();
  const showPF = ["admin","delivery_manager"].includes(_mrResolvedRole);
  const projects = showPF ? await getScopedProjects(user.email, false) : [];

  main.innerHTML = `
    <div class="page-header">
      <h2>Market Report Builder</h2>
      <div class="page-header-actions">
        <button class="btn-secondary" onclick="showMarketReportLibrary()">
          &larr; Back to Library</button>
        <button class="btn-secondary" id="mr-save-btn" onclick="mrSave()">
          Save</button>
        <button class="btn-secondary" onclick="mrPreview()">Preview</button>
        <button class="print-btn" onclick="mrExportPdf()">
          &#8856; Export PDF</button>
      </div>
    </div>
    <div class="rb-shell">
      <div class="rb-sidebar" id="mr-sidebar">
        ${mrRenderSidebar(roles, projects, showPF)}
      </div>
      <div class="rb-canvas" id="mr-canvas">
        <p class="no-data" style="padding:32px">
          Complete the fields on the left and click
          <strong>Generate Report</strong>.
        </p>
      </div>
    </div>
    <div id="mr-saved-modal" class="rb-modal" style="display:none"></div>
  `;
}

function mrRenderSidebar(roles, projects, showProjectFilter) {
  const sel = (id, cur) => id === cur ? " selected" : "";
  const projectOpts = projects.map(p =>
    `<option value="${p.id}"${sel(String(p.id), _mrProjectId)}>
      ${p.CustomerName}</option>`
  ).join("");
  const roleOpts = roles.map(r =>
    `<option value="${r.id}"${sel(String(r.id), _mrRoleId)}>
      ${r.RoleTitle}</option>`
  ).join("");

  return `
    <div class="rb-config">
      <div class="rb-section-label">Report Title</div>
      <input id="mr-title" class="rb-input" type="text"
        placeholder="e.g. Momentum x Client — Role Market Report (London) — Jun 2026"
        value="${_mrTitle || ""}"
        oninput="_mrTitle = this.value; this.dataset.autoSuggested = 'false'">
      <div class="rb-section-label"
           style="font-size:11px;color:var(--text-muted);margin-top:2px">
        Autogenerated — editable after report generation
      </div>

      ${showProjectFilter ? `
        <div class="rb-section-label">Project</div>
        <select class="rb-select" onchange="mrSetProject(this.value)">
          <option value="">— select project —</option>
          ${projectOpts}
        </select>` : ""}

      <div class="rb-section-label">Role</div>
      <select class="rb-select" id="mr-role-select"
        onchange="_mrRoleId = this.value; mrSuggestTitle(this)">
        <option value="">— select role —</option>
        ${roleOpts}
      </select>

      <div class="rb-section-label">Total Addressable Market (TAM)</div>
      <input id="mr-tam" class="rb-input" type="number" min="0"
        placeholder="e.g. 500"
        value="${_mrTam || ""}"
        oninput="_mrTam = parseInt(this.value) || null">

      <button class="btn-primary"
        style="margin-top:20px;width:100%"
        onclick="mrGenerate()">Generate Report</button>
    </div>
  `;
}

async function mrSetProject(projectId) {
  _mrProjectId = projectId;
  _mrRoleId    = null;
  const roles  = projectId ? await getRolesForProject(projectId) : [];
  const sel    = document.getElementById("mr-role-select");
  if (!sel) return;
  sel.innerHTML = '<option value="">— select role —</option>' +
    roles.map(r =>
      `<option value="${r.id}">${r.RoleTitle}</option>`
    ).join("");
}

async function mrGenerate() {
  const canvas = document.getElementById("mr-canvas");
  if (!_mrRoleId) {
    canvas.innerHTML =
      '<p class="no-data" style="padding:32px">Please select a role.</p>';
    return;
  }
  if (!_mrTam || _mrTam <= 0) {
    canvas.innerHTML =
      '<p class="no-data" style="padding:32px">Please enter a TAM value greater than 0.</p>';
    return;
  }
  canvas.innerHTML =
    '<p class="no-data" style="padding:32px">Loading...</p>';

  const roleId = parseInt(_mrRoleId);
  const [activity, role, rejections] = await Promise.all([
    getWeeklyActivity(null, roleId),
    getItem("Roles", roleId),
    getRejectedOffers(roleId),
  ]);
  _mrData = { activity, role, rejections };

  const totalOutreach  = sumField(activity, "Outreach");
  const totalResponses = sumField(activity, "Responses");
  const pctContacted   = Math.round((totalOutreach  / _mrTam) * 100);
  const pctResponded   = Math.round((totalResponses / _mrTam) * 100);
  const daysOpen = role.OpenDate
    ? Math.floor((Date.now() - new Date(role.OpenDate)) / 86400000)
    : null;

  const pipeline = {
    Screened:    sumField(activity, "Screened"),
    Submitted:   sumField(activity, "Submitted"),
    "IV1":       sumField(activity, "Interview1"),
    "IV2+":      sumField(activity, "Interview2Plus"),
    "Final IV":  sumField(activity, "FinalInterview"),
    Offers:      sumField(activity, "Offers"),
    Hires:       sumField(activity, "Hires"),
  };

  canvas.innerHTML = mrRenderCanvas({
    title: _mrTitle, tam: _mrTam,
    pctContacted, pctResponded, daysOpen,
    pipeline, rejections, obsHtml: _mrObs,
  });
  mrInitEditor();
}

function mrRenderCanvas({ title, tam, pctContacted, pctResponded,
                          daysOpen, pipeline, rejections, obsHtml }) {
  const kpis = [
    { label: "Total Addressable Market", value: tam.toLocaleString() },
    { label: "% of TAM Contacted",        value: pctContacted + "%" },
    { label: "% of TAM Responded",         value: pctResponded + "%" },
    { label: "Days Open",                  value: daysOpen !== null ? daysOpen : "—" },
  ];
  const kpiHtml = kpis.map(k =>
    `<div class="kpi-card">
       <div class="kpi-value">${k.value}</div>
       <div class="kpi-label">${k.label}</div>
     </div>`).join("");

  const colW = `style="width:${Math.floor(100/Object.keys(pipeline).length)}%;text-align:center"`;
  const pHeaders = Object.keys(pipeline).map(h => `<th ${colW}>${h}</th>`).join("");
  const pValues  = Object.values(pipeline).map(v => `<td ${colW}>${v}</td>`).join("");

  const rejHtml = rejections.length ? `
    <div class="print-avoid-break" style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px 24px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.06)">
      <div style="font-size:15px;font-weight:600;color:var(--brand);margin:0 0 16px 0;padding-bottom:8px;border-bottom:1px solid var(--border-subtle)">Offer Rejection Reasons</div>
      <table class="data-table"><thead><tr>
        <th>Candidate</th><th>Role</th><th>Reason</th><th>Detail</th>
      </tr></thead><tbody>
        ${rejections.map(r =>
          `<tr>
            <td>${r.CandidateName || "—"}</td>
            <td>${r.RoleTitle     || "—"}</td>
            <td>${r.Reason        || "—"}</td>
            <td>${r.Detail        || "" }</td>
          </tr>`).join("")}
      </tbody></table>
    </div>` : "";

  return `
    <style>
      #mr-obs-editor:empty:before {
        content: attr(data-placeholder);
        color: var(--text-faint); font-style: italic; pointer-events: none;
      }
    </style>
    ${title ? `<h2 class="rb-report-title">${title}</h2>` : ""}

    <div class="print-avoid-break" style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px 24px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.06)">
      <div style="font-size:15px;font-weight:600;color:var(--brand);margin:0 0 16px 0;padding-bottom:8px;border-bottom:1px solid var(--border-subtle)">Market Overview</div>
      <div class="kpi-strip">${kpiHtml}</div>
    </div>

    <div class="print-avoid-break" style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px 24px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.06)">
      <div style="font-size:15px;font-weight:600;color:var(--brand);margin:0 0 16px 0;padding-bottom:8px;border-bottom:1px solid var(--border-subtle)">Resulting Pipeline Activity</div>
            <table class="data-table" style="width:100%;margin:0">
        <thead><tr>${pHeaders}</tr></thead>
        <tbody><tr>${pValues}</tr></tbody>
      </table>
    </div>

    ${rejHtml}

    <div class="print-avoid-break" style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px 24px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.06)">
      <div class="rb-block rb-block-text">
        <div class="rb-rt-wrapper">
          <div class="rb-rt-toolbar" id="mr-obs-toolbar">
            <button type="button"
              onclick="mrFormat('bold')"><b>B</b></button>
            <button type="button"
              onclick="mrFormat('italic')"><i>I</i></button>
            <button type="button"
              onclick="mrFormat('underline')"><u>U</u></button>
            <button type="button"
              onclick="mrFormat('insertUnorderedList')">&#8226; List</button>
            <button type="button"
              onclick="mrFormat('insertOrderedList')">1. List</button>
            <button type="button"
              onclick="mrFormatBlock('H3')">Heading</button>
            <button type="button"
              onclick="mrFormatBlock('P')">Body Text</button>
            ${rtTableToolbarButtonHtml()}
          </div>
          <div id="mr-obs-editor" class="rb-richtext"
               contenteditable="true"
               style="min-height:200px;caret-color:var(--brand);cursor:text;padding:8px 10px"
               data-placeholder="Add observations &amp; recommendations here..."
               oninput="_mrObs = this.innerHTML; mrUpdateToolbarState()"
               onkeyup="mrUpdateToolbarState()"
               onmouseup="mrUpdateToolbarState()">${obsHtml || ""}</div>
        </div>
      </div>
    </div>
  `;
}

function mrFormat(cmd) {
  document.execCommand(cmd, false, null);
  mrUpdateToolbarState();
}

function mrFormatBlock(tag) {
  document.execCommand("formatBlock", false, tag);
  mrUpdateToolbarState();
}

function mrUpdateToolbarState() {
  const toolbar = document.getElementById("mr-obs-toolbar");
  rtUpdateToolbarState(toolbar, "mrFormat", "mrFormatBlock");
}

function mrInitEditor() {
  // Editor is ready as soon as the canvas renders.
  // mrUpdateToolbarState() fires on keyup/mouseup via the oninput binding.
  // No additional init required.
}

async function mrSave() {
  const title = document.getElementById("mr-title")?.value?.trim();
  if (!title)     { toast("Please enter a report title before saving.", { type: 'error' }); return; }
  if (!_mrRoleId) { toast("Please select a role before saving.", { type: 'error' });        return; }

  const user    = getCurrentUser();
  const payload = {
    Title:          title,
    RoleID:         parseInt(_mrRoleId),
    ProjectID:      _mrProjectId ? parseInt(_mrProjectId) : null,
    TAM:            _mrTam,
    Observations:   _mrObs,
    CreatedByEmail: user.email,
    RoleName:       _mrData?.role?.RoleTitle    || "",
    CustomerName:   _mrData?.role?.CustomerName || "",
  };

  if (_mrReportId) {
    await updateMarketReport(_mrReportId, payload);
  } else {
    const result = await createMarketReport(payload);
    _mrReportId  = result.id;
  }

  const btn = document.getElementById("mr-save-btn");
  if (btn) {
    btn.textContent = "Saved ✓";
    setTimeout(() => { btn.textContent = "Save"; }, 2000);
  }
}

// ── Entry point — the library (N-245) ──────────────────────────────
// Unscoped by design (decided with Chris, 18 Sep 2026): every user with
// Market Analytics module access sees every saved report, so there is no
// visibility filter here, unlike showReportBuilderLibrary/showBriefingPackLibrary.
async function showMarketReportLibrary() {
  const main = document.getElementById("main-content");
  main.innerHTML = '<div class="page-header"><h2>Market Report Library</h2></div><p>Loading...</p>';

  try {
    const [reports, roles, projects, displayMap] = await Promise.all([
      getMarketReports(),
      getAllRoles(),
      getProjects(false),
      getTalentPartnerDisplayMap(),
    ]);

    // report.CustomerName is unreliable (mrSave() has always saved it blank
    // — see N-245 fix 2 notes) and report.ProjectID is only ever set when
    // the admin/DM project filter was used, so resolve the client through
    // the report's RoleID instead — required on every report, and every
    // Roles item carries a real ProjectID.
    const roleProjectMap = {};
    roles.forEach(r => { roleProjectMap[String(r.id)] = String(r.ProjectID || ''); });
    _mrProjectMap = {};
    projects.forEach(p => { _mrProjectMap[String(p.id)] = p.CustomerName || ''; });
    _mrRoleProjectMap = roleProjectMap;

    _mrLibraryCache = reports;
    _mrTpMap        = displayMap;
    _mrRenderLibrary();
  } catch (e) {
    main.innerHTML = pageErrorBlock({ message: e.message, retryOnClick: 'showMarketReportLibrary()' });
    if (window.lucide) lucide.createIcons();
  }
}

// Single resolver for grouping, filter options and filter matching, so all
// three agree. Resolved via RoleID -> Roles.ProjectID -> Projects.CustomerName
// (see showMarketReportLibrary) rather than the report's own CustomerName/
// ProjectID fields, neither of which is reliably populated.
function _mrReportClient(report) {
  const projectId = _mrRoleProjectMap[String(report.RoleID)];
  return (projectId && _mrProjectMap[projectId]) || 'Unassigned';
}

function mrLibraryFilterChanged(value) {
  _mrLibraryFilter = value;
  _mrRenderLibrary();   // re-render from cache, no refetch
}

function _mrLibraryClientOptions() {
  const values = [...new Set(_mrLibraryCache.map(_mrReportClient))]
    .sort((a, b) => a === 'Unassigned' ? 1 : b === 'Unassigned' ? -1 : a.localeCompare(b));
  return ['<option value="">All</option>'].concat(values.map(v =>
    `<option value="${escAttr(v)}"${v === _mrLibraryFilter ? ' selected' : ''}>${escHtml(v)}</option>`
  )).join('');
}

function _mrRenderLibrary() {
  const me      = (getCurrentUser().email || '').toLowerCase();
  const isAdmin = _mrResolvedRole === 'admin';
  const reports = _mrLibraryCache.filter(r => !_mrLibraryFilter || _mrReportClient(r) === _mrLibraryFilter);

  const groups = {};
  reports.forEach(r => {
    const client = _mrReportClient(r);
    (groups[client] = groups[client] || []).push(r);
  });

  const clientOrder = Object.keys(groups)
    .sort((a, b) => a === 'Unassigned' ? 1 : b === 'Unassigned' ? -1 : a.localeCompare(b));

  const rows = reports.length
    ? clientOrder.map(client => {
        const list = groups[client].slice()
          .sort((a, b) => (a.ReportTitle || '').localeCompare(b.ReportTitle || ''));
        const reportRows = list.map(r => {
          const owner     = r.CreatedByEmail || '';
          const canDelete = isAdmin || owner.toLowerCase() === me;
          return `
        <tr>
          <td>${escHtml(r.ReportTitle || '—')}</td>
          <td>${escHtml(r.RoleName || '—')}</td>
          <td>${escHtml(_mrTpMap[owner.toLowerCase()] || owner || '—')}</td>
          <td>
            <div class="row-actions">
              <button class="btn-secondary" onclick="mrLoadReport(${r.id})">Open</button>
              <button class="btn-secondary" onclick="mrCopyReportAction(${r.id}, this)">Copy</button>
              ${canDelete ? `<button class="btn-secondary" onclick="mrDeleteReport(${r.id}, '${escJsAttr(r.ReportTitle || '')}')">Delete</button>` : ''}
            </div>
          </td>
        </tr>`;
        }).join('');
        return `
        <tr class="bp-lib-client-row">
          <td colspan="4"><strong>${escHtml(client)}</strong> <span class="bp-lib-count">${list.length}</span></td>
        </tr>${reportRows}`;
      }).join('')
    : emptyStateRow({
        colspan: 4,
        icon: 'folder',
        message: _mrLibraryCache.length
          ? 'No reports match the current filter.'
          : 'No market reports saved yet.',
      });

  const main = document.getElementById('main-content');
  main.innerHTML = `
    <div class="page-header">
      <h2>Market Report Library</h2>
      <div class="page-header-actions">
        <button class="btn-primary" onclick="mrStartNewReport()">+ New Report</button>
      </div>
    </div>
    <div class="table-toolbar">
      ${listControlsBar([`
        <div class="form-group project-filter-select">
          <label>Client</label>
          <select onchange="mrLibraryFilterChanged(this.value)">${_mrLibraryClientOptions()}</select>
        </div>`])}
    </div>
    <div class="table-scroll">
      <table class="data-table">
        <thead><tr>
          <th>Title</th><th>Role</th><th>Owner</th><th></th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
  `;
  if (window.lucide) lucide.createIcons();
}

// Real gotcha, not boilerplate: _mrReportId/_mrRoleId/etc. are module-level
// and persist across SPA navigations — renderMarketReport() never clears
// them. This must be the ONLY way the Library's "+ New Report" reaches the
// builder; never wire it to call renderMarketReport() directly, or a blank
// report silently inherits whatever was last open (same class of bug as
// N-244's rbStartNewReport()).
function mrStartNewReport() {
  _mrReportId  = null;
  _mrRoleId    = null;
  _mrProjectId = null;
  _mrTam       = null;
  _mrTitle     = "";
  _mrObs       = "";
  _mrData      = null;
  renderMarketReport();
}

async function mrCopyReportAction(id, btn) {
  setButtonLoading(btn);
  try {
    const created = await copyMarketReport(id, getCurrentUser().email);
    await mrLoadReport(created.id);
  } catch (e) {
    toast('Could not copy that report: ' + e.message, { type: 'error' });
  } finally {
    clearButtonLoading(btn);
  }
}

async function mrDeleteReport(id, title) {
  if (!(await confirmModal({
    message: `Delete "${title}"? This cannot be undone.`,
    confirmLabel: 'Delete', danger: true,
  }))) return;
  try {
    await deleteItem("MarketReports", id);
  } catch (e) {
    toast("Could not delete that report: " + e.message, { type: 'error' });
    return;
  }
  showMarketReportLibrary();
}

async function mrLoadReport(id) {
  const report = await getMarketReportById(id);
  _mrReportId  = id;
  _mrRoleId    = report.RoleID    ? String(report.RoleID)    : null;
  _mrProjectId = report.ProjectID ? String(report.ProjectID) : null;
  _mrTam       = report.TAM       ? parseFloat(report.TAM)   : null;
  _mrTitle     = report.ReportTitle || "";
  _mrObs       = report.Observations || "";
  await renderMarketReport();
  await mrGenerate();
}

function mrPreview() {
  if (!_mrData) {
    toast("Generate the report first before previewing.", { type: 'error' });
    return;
  }
  const obsEl = document.getElementById("mr-obs-editor");
  if (obsEl) _mrObs = obsEl.innerHTML;

  const modal = document.getElementById("mr-saved-modal");
  modal.style.display = "flex";
  modal.innerHTML = `
    <div class="rb-modal-inner"
         style="max-width:860px;width:90%">
      <div class="rb-report-preview">${mrRenderPrintCanvas()}</div>
      <div style="display:flex;gap:8px;margin-top:16px">
        <button class="print-btn" onclick="mrExportPdf()">Export PDF</button>
        <button class="btn-secondary"
          style="height:36px;line-height:1;padding:0 18px"
          onclick="document.getElementById('mr-saved-modal').style.display='none'">Close</button>
      </div>
    </div>
  `;
}

async function mrExportPdf() {
  if (!_mrData) {
    toast("Generate the report first before exporting.", { type: 'error' });
    return;
  }
  const obsEl = document.getElementById("mr-obs-editor");
  if (obsEl) _mrObs = obsEl.innerHTML;

  const title = _mrTitle || "Market Report";
  const main  = document.getElementById("main-content");

  main.innerHTML = mrRenderPrintCanvas();

  printPage(title, true, "Market Report");
  setTimeout(() => {
    const canvas = document.getElementById("mr-canvas");
    if (canvas) {
      const act = _mrData.activity;
      canvas.innerHTML = mrRenderCanvas({
        title: _mrTitle, tam: _mrTam,
        pctContacted: Math.round((sumField(act, "Outreach")  / _mrTam) * 100),
        pctResponded: Math.round((sumField(act, "Responses") / _mrTam) * 100),
        daysOpen: _mrData.role.OpenDate
          ? Math.floor((Date.now() - new Date(_mrData.role.OpenDate)) / 86400000)
          : null,
        pipeline: {
          Screened:   sumField(act, "Screened"),
          Submitted:  sumField(act, "Submitted"),
          "IV1":      sumField(act, "Interview1"),
          "IV2+":     sumField(act, "Interview2Plus"),
          "Final IV": sumField(act, "FinalInterview"),
          Offers:     sumField(act, "Offers"),
          Hires:      sumField(act, "Hires"),
        },
        rejections: _mrData.rejections,
        obsHtml: _mrObs,
      });
      mrInitEditor();
    } else {
      renderMarketReport().then(() => mrGenerate());
    }
  }, 500);
}

function mrRenderPrintCanvas() {
  if (!_mrData) return "";
  const { activity, role, rejections } = _mrData;

  const totalOutreach  = sumField(activity, "Outreach");
  const totalResponses = sumField(activity, "Responses");
  const pctContacted   = Math.round((totalOutreach  / _mrTam) * 100);
  const pctResponded   = Math.round((totalResponses / _mrTam) * 100);
  const daysOpen = role.OpenDate
    ? Math.floor((Date.now() - new Date(role.OpenDate)) / 86400000)
    : null;

  const pipeline = {
    Screened:   sumField(activity, "Screened"),
    Submitted:  sumField(activity, "Submitted"),
    "IV1":      sumField(activity, "Interview1"),
    "IV2+":     sumField(activity, "Interview2Plus"),
    "Final IV": sumField(activity, "FinalInterview"),
    Offers:     sumField(activity, "Offers"),
    Hires:      sumField(activity, "Hires"),
  };

  const kpis = [
    { label: "Total Addressable Market", value: _mrTam.toLocaleString() },
    { label: "% of TAM Contacted",        value: pctContacted + "%" },
    { label: "% of TAM Responded",         value: pctResponded + "%" },
    { label: "Days Open",                  value: daysOpen !== null ? daysOpen : "\u2014" },
  ];
  const kpiHtml = kpis.map(k =>
    `<div class="kpi-card">
       <div class="kpi-value">${k.value}</div>
       <div class="kpi-label">${k.label}</div>
     </div>`).join("");

  const colPct = Math.floor(100 / Object.keys(pipeline).length);
  const colW = `style="width:${colPct}%;text-align:center"`;
  const pHeaders = Object.keys(pipeline).map(h => `<th ${colW}>${h}</th>`).join("");
  const pValues  = Object.values(pipeline).map(v => `<td ${colW}>${v}</td>`).join("");

  const rejHtml = rejections.length ? `
    <div class="print-avoid-break" style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px 24px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.06)">
      <div style="font-size:15px;font-weight:600;color:var(--brand);margin:0 0 16px 0;padding-bottom:8px;border-bottom:1px solid var(--border-subtle)">Offer Rejection Reasons</div>
      <table class="data-table" style="width:100%"><thead><tr>
          <th>Candidate</th><th>Role</th><th>Reason</th><th>Detail</th>
        </tr></thead><tbody>
          ${rejections.map(r =>
            `<tr>
              <td>${r.CandidateName || "\u2014"}</td>
              <td>${r.RoleTitle     || "\u2014"}</td>
              <td>${r.Reason        || "\u2014"}</td>
              <td>${r.Detail        || ""      }</td>
            </tr>`).join("")}
        </tbody></table>
      </div>
    </div>` : "";

  return `
    ${_mrTitle ? `<h2 class="rb-report-title" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${_mrTitle}</h2>` : ""}

    <div class="print-avoid-break" style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px 24px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.06)">
      <div style="font-size:15px;font-weight:600;color:var(--brand);margin:0 0 16px 0;padding-bottom:8px;border-bottom:1px solid var(--border-subtle)">Market Overview</div>
      <div class="kpi-strip">${kpiHtml}</div>
    </div>

    <div class="print-avoid-break" style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px 24px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.06)">
      <div style="font-size:15px;font-weight:600;color:var(--brand);margin:0 0 16px 0;padding-bottom:8px;border-bottom:1px solid var(--border-subtle)">Resulting Pipeline Activity</div>
      <table class="data-table" style="width:100%;margin:0">
        <thead><tr>${pHeaders}</tr></thead>
        <tbody><tr>${pValues}</tr></tbody>
      </table>
    </div>

    ${rejHtml}

    <div class="print-avoid-break" style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px 24px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.06)">
      <div class="rb-richtext" style="min-height:120px;padding:8px 10px">${_mrObs || ""}</div>
    </div>
  `;
}

function mrSuggestTitle(roleSelect) {
  const titleInput = document.getElementById("mr-title");
  if (!titleInput) return;

  const roleName    = roleSelect.options[roleSelect.selectedIndex]?.text || "";
  const projectSel  = document.getElementById("mr-sidebar")
                        ?.querySelector("select.rb-select");
  const customerName = projectSel && projectSel !== roleSelect
    ? projectSel.options[projectSel.selectedIndex]?.text || ""
    : "";

  const now     = new Date();
  const month   = now.toLocaleString("default", { month: "long" });
  const year    = now.getFullYear();
  const dateStr = `${month} ${year}`;

  const suggested = customerName
    ? `${customerName} x Momentum - ${roleName} (${dateStr})`
    : `Momentum - ${roleName} (${dateStr})`;

  // Only overwrite if blank or was a previous auto-suggestion
  if (!_mrTitle || titleInput.dataset.autoSuggested === "true") {
    titleInput.value       = suggested;
    titleInput.dataset.autoSuggested = "true";
    _mrTitle               = suggested;
  }
}
